services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:latest
    container_name: frappuccino_postgres
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
      # - frappuccino-data-pq:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
# volumes:
  # frappuccino-data-pq: